services:
  app1:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app1
    environment:
      - INSTANCE_NAME=app1
    networks: [lbnet]
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:5000/healthz').read()"]
      interval: 10s
      timeout: 3s
      retries: 3

  app2:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app2
    environment:
      - INSTANCE_NAME=app2
    networks: [lbnet]
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:5000/healthz').read()"]
      interval: 10s
      timeout: 3s
      retries: 3

  app3:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app3
    environment:
      - INSTANCE_NAME=app3
    networks: [lbnet]
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:5000/healthz').read()"]
      interval: 10s
      timeout: 3s
      retries: 3

  app4:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app4
    environment:
      - INSTANCE_NAME=app4
    networks: [lbnet]
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:5000/healthz').read()"]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx-lb
    depends_on:
      - app1
      - app2
      - app3
      - app4
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks: [lbnet]

networks:
  lbnet:
    driver: bridge
